package com.example.alaaripatient.editprofile

data class EditProfileModal(
    val _id: String,
    val age: String,
    val alternateContact: String,
    val area: String,
    val city: String,
    val country: String,
    val createdBy: String,
    val createdOn: Long,
    val dialCode: String,
    val email: String,
    val facebookUrl: String,
    val firstName: String,
    val fullName: String,
    val gender: String,
    val isActive: Boolean,
    val lastName: String,
    val linkedin: String,
    val mobileNumber: String,
    val modifiedBy: String,
    val modifiedOn: Long,
    val mrNumber: String,
    val password: String,
    val selectLanguage: String,
    val street: String,
    val title: String,
    val totalExperience: String,
    val userType: String,
    val verified: String
)